[package]
name = "advent-2024"
version = "0.1.0"
authors = ["Sol Toder <ajaxgb@gmail.com>"]
edition = "2021"

[[bin]]
name = "day01"
path = "src/day01/main.rs"

[dependencies]
itertools = "0.13.0"
thiserror = "2.0.7"
